//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseholdBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banka
    {
        public int bankaID { get; set; }
        public string adi { get; set; }
        public string slogan { get; set; }
        public string adres { get; set; }
        public string tel { get; set; }
        public string il { get; set; }
    }
}
