//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseholdBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HGS
    {
        public int hgsID { get; set; }
        public string musTCKN { get; set; }
        public Nullable<int> bakiye { get; set; }
        public Nullable<bool> aktifmi { get; set; }
    }
}
