//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseholdBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islem
    {
        public int islemID { get; set; }
        public string hesapNo { get; set; }
        public string hesapEkNo { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string islemTipi { get; set; }
        public string platform { get; set; }
    }
}
