//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseholdBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public string tcKimlikNo { get; set; }
        public string tamAdi { get; set; }
        public string ePosta { get; set; }
        public string sifre { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public string hesapNo { get; set; }
    }
}
